services:
  # 1.2 MariaDB (Puerto 3306) - Requisito del PDF
  db:
    image: docker.io/library/mariadb:latest
    container_name: mariadb_lab
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "88888888"
      MYSQL_DATABASE: db01
    volumes:
      - ./db_data:/var/lib/mysql

  # phpMyAdmin (Puerto 8085) - Para gestionar tu DB
  phpmyadmin:
    image: docker.io/library/phpmyadmin:latest
    container_name: phpmyadmin_web
    restart: always
    ports:
      - "8085:80"
    environment:
      - PMA_HOST=db
      - PMA_ARBITRARY=1
    depends_on:
      - db

  # 1.2 Apache + PHP (Puerto 8083) - Requisito del PDF
  apache-php:
    image: docker.io/library/php:8.2-apache
    container_name: apache_php_lab
    restart: always
    ports:
      - "8083:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
